### ISSUE TITLE
Build Error  ? defaultFirebaseAppName ?

### ISSUE THREAD

**Issue by volkankoc** [sailesh307/health_app#1]
Error code

: Error: 'ehthrow' isn't a type.
../…/method_channel/method_channel_firebase.dart:127
          ehthrow duplicateApp(defaultFirebaseAppName);
          ^^^^^^^
: Error: Expected ';' after this.
../…/method_channel/method_channel_firebase.dart:127
          ehthrow duplicateApp(defaultFirebaseAppName);
                  ^^^^^^^^^^^^

**Comment by volkankoc** [comment]
I ran. Thank you. Topic can be closed

**Comment by sailesh307** [comment]
ok
